dependencies:
  - pip:
      - langchain_community==0.3.5
      - langchain==0.3.7
      - youtube-transcript-api==0.6.2
      - gql==3.5.0
      - langchain-text-splitters==0.3.2
      - langchain_chroma==0.1.4
      - langchain_openai==0.2.6
      - langchain_core==0.3.15
      - langgraph==0.2.45
      - gradio==5.5.0
